High Security Detection - False Positive
Fixing a line that is detected, and flagging as a false positive line, due to this module no longer being able to run with the affected version.

Test performed:
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qualysapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "qualysapi\__init__.py", line 6, in <module>
    from qualysapi.util import connect
  File "qualysapi\util.py", line 4, in <module>
    import qualysapi.config as qcconf
  File "qualysapi\config.py", line 173
    proxy_config += f":{proxy_port}"
                                   ^
SyntaxError: invalid syntax

Bandit Results:
----------------------------------
Code scanned:
        Total lines of code: 1158
        Total lines skipped (#nosec): 1

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 3.0
                Medium: 0.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 3.0
Files skipped (0):
ERROR: InvocationError for command 'E:\scripting_misc\qualysapi_builds\qualysapitests_clear-security-high\paragbaxi\qualysapi\.tox\security\Scripts\bandit.EXE' --recursive qualysapi/ (exited with code 1)
_______________________________________________________ summary _______________________________________________________
ERROR:   security: commands failed